#!/bin/bash
cd ups
number=0
out="<br>"

for i in *; do
  #if [ "$number" -eq "0" ]; then
  #  out="<img class="mySlides" src='ups/$number'>"
  #else
    out="$out<a href='upload.php?deleteMe=$number'><img class="mySlides" src='ups/$number'></a>"
  #fi
  let "number++"
done

echo $out